#!/usr/bin/env python
#  micropi.py
#
#  Copyright 2016  Nathan Taylor
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#
import os

HOMEDIR = os.path.expanduser('~')
MICROPIDIR = os.path.join(HOMEDIR, '.micropi')

def delFolder(path):
    if os.path.exists(path):
        for i in os.listdir(path):
            if os.path.isdir(os.path.join(path, i)):
                delFolder(os.path.join(path, i))
                os.rmdir(os.path.join(path, i))
            else:
                print(os.path.join(path, i))
                os.remove(os.path.join(path, i))

delFolder(MICROPIDIR)
